#!/bin/bash

source /etc/lsb-release

sudo apt-key adv --keyserver keys.gnupg.net --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 

sudo add-apt-repository "deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo $DISTRIB_CODENAME main" -u

sudo apt-get install apt-utils -y
sudo apt-get install librealsense2-utils librealsense2-dev -y
