#!/usr/bin/env python3

import json, sys
import urllib.request

def get_quote(symbol):
  url = 'https://coinmarketcap.com/currencies/' + symbol
  request = urllib.request.urlopen(url)
  try:
    html = request.read().decode('utf-8')
    results = re.search(r'data-usd="(.*)"', s)
    if results:
        return float(results.group(1))
    else:
        return -1
  except:
    print("Could not retrieve quote")
    return None

if __name__ == "__main__":
    symbols = sys.argv[1:]
    for symbol in symbols:
        symbol = symbol.upper()
        quote = get_quote(symbol)
        if quote:
          print(symbol + " " + quote.get('LastTradePriceOnly', 0) + " " + quote.get('Change', 0))

