#!/usr/bin/env python3

import os, sys, uuid

COMMIT = "--commit" in sys.argv

if not COMMIT:
    print("Dry run, run with --commit to commit")

f = open(".original_names", "a")

for filename in os.listdir('.'):
    if filename.startswith("."):
        continue
    extension = filename[filename.find("."):]
    filename_new = str(uuid.uuid4()) + extension
    f.write("%s %s\n" % (filename, filename_new))
    if not COMMIT:
        print("[dry run] rename %s to %s" % (filename, filename_new))
    else:
        print("[wet run] rename %s to %s" % (filename, filename_new))
        os.rename(filename, filename_new)


f.close()
