#!/usr/bin/env python3

import os, sys, uuid

f = open(".original_names", "a")

for filename in os.listdir('.'):
    if filename.startswith("."):
        continue
    extension = filename[filename.find("."):]
    filename_new = str(uuid.uuid4()) + extension
    print("%s %s" % (filename, filename_new))
    f.write("%s %s\n" % (filename, filename_new))
    os.rename(filename, filename_new)


f.close()
