#!/bin/bash
if docker ps | grep -q dheera_noetic
then
    docker exec -it dheera_noetic /bin/bash
else
    echo "(starting)"
    docker rm dheera_noetic 2>/dev/null
    docker run \
        -e DISPLAY \
        -e DBUS_SESSION_BUS_ADDRESS \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v /home/dheera:/home/dheera \
        -v $XAUTHORITY:/root/.Xauthority \
        --net=host \
        --name dheera_noetic \
        --privileged \
        -it dheera:noetic /bin/bash
fi

