#!/usr/bin/zsh
# based on https://gist.github.com/yellowled/1439610

mkdir out

IN=$1
OUT=$(echo $1 | sed 's/^\(.*\)\.[a-zA-Z0-9]*$/\1/')

#ffmpeg -i $IN -f webm -r:v 24 -vcodec libvpx -an out/$OUT.webm
#ffmpeg -i $IN -f mp4  -r:v 24 -vcodec h264 -ac 2 -an -vcodec libx264 -f mp4 out/$OUT.mp4
#ffmpeg -i $IN -f ogv  -r:v 24 -ac 2 -an -vcodec libx264 -f mp4 out/$OUT.mp4

ffmpeg -i $IN -c:v h264 -an -r:v 24 -b:v 800k out/$OUT.mp4 # Convert to MP4
ffmpeg -i $IN -c:v libtheora -an -r:v 24 -b:v 1500k out/$OUT.ogv # Convert to OGV
ffmpeg -i $IN -c:v libvpx -an -r:v 24 -b:v 800k out/$OUT.webm # Convert to Webm

# ogg (if you want to support older Firefox)
#ffmpeg2theora $IN -o out/$OUT.ogv --videoquality 5 --audioquality 0  --frontend
