#!/usr/bin/env python3
import cv2
import sys
import numpy
import time

def hex_to_rgb(value):
    value = value.lstrip('#')
    lv = len(value)
    return tuple(int(value[i:i + lv // 3], 16) for i in reversed(range(0, lv, lv // 3)))

if __name__ == "__main__":

    if len(sys.argv) < 4:
        print("Usage: imagesed infile.png outfile.png ff00ff:000000 00ffff:010101 ...")
        print("Like sed, but for images. Maps one color to another.")
        exit()

    img = cv2.imread(sys.argv[1])
 
    replace_table = [(0,0,0)] * 16777216
  
    for replacement in sys.argv[3:]:
        replace_from, replace_to = replacement.split(':')
        replace_from_rgb = hex_to_rgb(replace_from)
        replace_to_rgb = hex_to_rgb(replace_to)
        replace_table[replace_from_rgb[0] + replace_from_rgb[1]*256 + replace_from_rgb[2]*65536] = replace_to_rgb

    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            index = img[i,j,0] + img[i,j,1]*256 + img[i,j,2]*65536
            img[i,j] = replace_table[index]

    cv2.imwrite(sys.argv[2], img)
