#!/bin/bash

for i in 1 2 3 4 5 6 7 8 9 10
do
    # keyboard
    hidapitester --vidpid 046D:C52B --open --length 7 --send-output 0x10,0x03,0x09,0x11,0x01,0x00,0x00

    # mouse
    hidapitester --vidpid 046D:C52B --open --length 7 --send-output 0x10,0x01,0x0a,0x1a,0x01

    sleep 0.05
done
