#!/usr/bin/env python

# Shortcut to ldapsearch.

# Find out who all work in 36-469
# mitsearch roomNumber=36-469

# Find out who has Kerberos id dheera
# mitsearch uid=dheera

# Search by last and first name
# mitsearch sn=venkatraman givenName=dheera

# Find out who has (listed) phone number xxx-xxx-xxxx
# mitsearch telephoneNumber=xxx-xxx-xxxx

# etc.

from subprocess import call
import sys

query = "(&" + "".join(map(lambda x: "("+x+")", sys.argv[1:])) + ")"

call(["ldapsearch", "-LLL", "-x", "-h", "ldap-too.mit.edu", "-b", "ou=users,ou=moira,dc=mit,dc=edu", query])
