#!/usr/bin/env python

# Shortcut to ldapsearch.

# Find out who all work in 36-469
# mitsearch roomNumber=36-469

# Find out who has Kerberos id dheera
# mitsearch uid=dheera

# Find out who has (listed) phone number xxx-xxx-xxxx
# mitsearch telephoneNumber=xxx-xxx-xxxx

# etc.


from subprocess import call
import sys

call(["ldapsearch", "-LLL", "-x", "-h", "ldap-too.mit.edu", "-b", "ou=users,ou=moira,dc=mit,dc=edu", sys.argv[1]])
