#!/usr/bin/env python3

import os, sys, base64, time

try:
  from getpass import getpass
except ImportError:
  os.system("sudo pip3 install getpass")

try:
  from passlib.utils.pbkdf2 import pbkdf2
except ImportError:
  os.system("sudo pip3 install passlib")

master_password = getpass();

table = {
  "yahoo.com":2,
}

if len(sys.argv)>2:
  n = int(sys.argv[2])
else:
  n = 0

thehash = pbkdf2(
  (master_password + "/" + sys.argv[1]).encode('utf-8'),
  b'',
  100000+n,
  keylen = 16
)

out_password = base64.b64encode(thehash)[0:12].decode('utf-8') + "$1Aa"

print(out_password)

