#!/usr/bin/perl

# My music player

while(1) {
  print "player> ";
  chomp($line=<stdin>);
  $command=-1;
  if($line ne "") {
    $command=0;
    if($line=~/^(s|straight) /) { $line=~s/^(s|straight) //;$command=0; }
    if($line=~/^(r|random) /) { $line=~s/^(r|random) //;$command=1; }
    if($line=~/^(l|ls|list) /) { $line=~s/^(l|ls|list) //;$command=2; }
    if($line=~/^(c|clear) /) { $line=~s/^(c|clear) //;$command=3; }
  }
  if($command==0 || $command==1) { sleep 1; }
  #if($command==0) { system("find ~/stuff/music/ | egrep -i '$line' | sort | play"); }
  #if($command==1) { system("find ~/stuff/music/ | egrep -i '$line' | rl | play"); }
  if($command==0) {
    system("find /net/data.dheera.net/stuff/music/ | egrep -i '$line' | sort > /tmp/playlist");
    system("cat /tmp/playlist > /tmp/playlist2");
    for($k=0;$k<30;$k++) {
      system("cat /tmp/playlist >> /tmp/playlist2");
    }
    system("mplayer -playlist /tmp/playlist2");
  }
  if($command==1) {
    system("find /net/data.dheera.net/stuff/music/ | egrep -i '$line' | rl > /tmp/playlist");
    system("cat /tmp/playlist > /tmp/playlist2");
    for($k=0;$k<30;$k++) {
      system("cat /tmp/playlist >> /tmp/playlist2");
    }
    system("mplayer -playlist /tmp/playlist2");
  }
  if($command==2) { system("find /net/stuff/music/ | egrep -i '$line'"); }
  if($command==3) { system("clear"); }
}
