#!/usr/bin/env python3

# Reads a Seek RevealPro radiometric tiff and outputs a 8-bit grayscale TIFF
# with scale:
# 0 -> -40 C
# 255 -> 88 C

import sys
import numpy
import PIL.Image

if len(sys.argv) == 2:
    infile = sys.argv[1]
    tmin = -40.
    tmax = 88.
elif len(sys.argv) == 4:
    infile = sys.argv[1]
    tmin = float(sys.argv[2])
    tmax = float(sys.argv[3])
else:
    print("Usage: seek2gray infile.tiff")
    print("Usage: seek2gray infile.tiff -40 88 (custom scale)")
    exit(1)

img = PIL.Image.open(infile)
img.seek(1)
outimg_data = numpy.rot90(numpy.reshape(list(img.getdata()), (240, 320)))
outimg_data = numpy.clip(outimg_data, tmin, tmax)
outimg_data_scaled = (255*((outimg_data - tmin)/(tmax-tmin))).astype(numpy.uint8)

img_out = PIL.Image.fromarray(outimg_data_scaled)
img_out.save(infile.replace('.tiff', '') + '.8b.tiff')
