#!/usr/bin/python

# Simple insecure TTS server for quick hacks

import tornado.ioloop
import tornado.web
import os, time, sys
import signal
import urllib
from espeak import espeak # sudo apt-get install espeak python-espeak

def signal_handler(signum, frame):
    print('exiting...')
    tornado.ioloop.IOLoop.instance().stop()
    print('done')


class MainHandler(tornado.web.RequestHandler):
    def get(self, text):
      print(urllib.unquote_plus(text))
      espeak.synth(urllib.unquote_plus(text))

application = tornado.web.Application([
    (r"/(.*)", MainHandler),
])

if __name__ == "__main__":
    application.listen(5010)
    signal.signal(signal.SIGINT, signal_handler)
    tornado.ioloop.IOLoop.instance().start()
