#!/bin/sh

# sshuttle with more sensible default options
# that should probably be default so you don't have to RTFM every time

# Usage: ./sshuttle-foo dheera@someserver.net
# (so simple!)

sshuttle --dns --no-latency-control --python /usr/bin/python -l 0.0.0.0 -vr $1 0/0

