#!/usr/bin/env python3

import json, sys
import urllib.request

WATCH_SYMBOL = "GOOG"

def get_quote(ticker_symbol):
  url = 'https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20yahoo.finance.quotes%20where%20symbol%20in%20(%22' + ticker_symbol + '%22)&format=json&diagnostics=true&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&callback='
  request = urllib.request.urlopen(url)
  try:
    data = json.loads(request.read().decode('utf-8'))
    return data.get('query', {}).get('results', {}).get('quote')
  except:
    print("Could not retrieve quote")
    return None
  
quote = get_quote(sys.argv[1])
if quote:
  print(quote.get('LastTradePriceOnly', 0) + " " + quote.get('Change', 0))

