#!/usr/bin/env python3

# Convert Facebook to WeChat sticker
# Requirements:
# apt-get install imagemagick gifsicle
# Usage:
# wget https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xpa1/t39.1997-6/p261x260/851593_279586375548961_1695481341_n.png -O sticker.png
# ./fb2wxsticker.py sticker.png 2 2
# (for a 2x2 sticker file)

import os, sys, subprocess
from fnmatch import fnmatch

fn_in = sys.argv[1]
fn_stem = fn_in[:-4]
fn_out = 'wx-' + fn_stem + '.gif'

tiles = [float(sys.argv[2]), float(sys.argv[3])]

size = subprocess.check_output(['identify', fn_in]) \
         .decode('utf-8').split(' ')[2].split('x')

size = list(map(int, size))
print(size)

subprocess.call(['convert',
  '-background', '#f0f0f0',
  '-flatten',
  '-dither', 'None',
  '-colors', '256',
  '-verbose',
  fn_in, 'temp-' + fn_stem + '.gif'])

subprocess.call(['convert',
  '-verbose',
  'temp-' + fn_stem + '.gif',
  '-crop', str(int(0.5+size[0]/tiles[0])) + 'x' + str(0.5+int(size[1]/tiles[1])),
  '+repage', 'temp-%d.gif'])

os.unlink('temp-' + fn_stem + '.gif')

gif_input_files = list(filter(
  lambda x:fnmatch(x, 'temp-*.gif'),
  os.listdir('.')
))

print(gif_input_files)

gif_data = subprocess.check_output(['gifsicle',
  '--colors=256',
  '--disposal=background',
  '--background=#F0F0F0',
  '--unoptimize',
  '--delay=15',
  '--loop'] + gif_input_files)

f = open(fn_out, 'wb')
f.write(gif_data)
f.close()

for fn in gif_input_files:
  os.unlink(fn)

gif_data = subprocess.check_output(['gifsicle',
  '--transparent=#F0F0F0',
  fn_out])

f = open(fn_out, 'wb')
f.write(gif_data)
f.close()

