#!/usr/bin/env python3
from blinkytape import BlinkyTape
import time
import psutil


blinky = BlinkyTape("/dev/lightdesk")
blinky.displayColor(15,15,15)

def mean(list):
    return sum(list)/len(list)

while True:
    #for i in range(25):
    #    blinky.sendPixel(cpu_light, 0, 255 - cpu_light)
    #blinky.show()

    time.sleep(0.5)
