FROM ros:noetic

RUN DEBIAN_FRONTEND=noninteractive sudo apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    vim \
    screen \
    htop \
    python3-pip \
    ros-noetic-desktop-full

