#!/usr/bin/env python3

# This script takes whatever is in the clipboard and displays it on screen as a QR code on screen
# Useful for copying URL from browser and scanning it with your phone

import pyperclip
import time
import qrcode
import threading
from tkinter import Toplevel, Tk, Label, PhotoImage

def show_qr(value):
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=5,
    )
    qr.add_data(value)
    img = qr.make_image(back_color=(255,255,255), fill_color=(0,0,0))
    img = img.resize((960, 960))
    img.save("/tmp/qr.png")
    show_image("/tmp/qr.png")

def show_image(img):
    win = Tk()
    
    win.attributes('-alpha', 0.8)
    win.iconify()
    screen_width = win.winfo_screenwidth()
    screen_height = win.winfo_screenheight()
    
    window = Toplevel(win)
    x = screen_width // 2 - 960 // 2
    y = screen_height // 2 - 960 // 2
    window.geometry(f"960x960+{x}+{y}")
    window.overrideredirect(1)
    
    photo = PhotoImage(file=img)
    
    label = Label(window, image=photo)
    label.pack()

    win.after(10000,lambda:win.destroy())

    win.mainloop()

current = pyperclip.paste()
show_qr(current)


