#!/usr/bin/env python3

import json
import sys
import pprint as pprint

with open(sys.argv[1]) as f:
    j = json.loads(f.read())

for item in sys.argv[2:]:
    try:
        item = int(item)
    except:
        pass
    j = j[item]

pprint.pprint(j)
