#!/usr/bin/env python3

import matplotlib.pyplot as plt
import numpy as np
import sys

latents = np.load(sys.argv[1])
if len(latents.shape) == 4:
    latents = latents[0]

row0 = np.hstack((latents[0], latents[1]))
row1 = np.hstack((latents[2], latents[3]))
display = np.vstack((row0, row1))
plt.imshow(display)
plt.show()
