#!/bin/bash

sudo apt update && sudo apt install curl gnupg2 lsb-release

# https://discourse.ros.org/t/ros-gpg-key-expiration-incident/20669/27
# ROS official said use this
sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
# but it didn't work but some dude in comments said do this instead
# welcome to 2021
sudo curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

sudo apt update
sudo apt install -y ros-galactic-desktop

sudo apt install -y python3-argcomplete

sudo pip install -U colcon-common-extensions
sudo pip install -U pytest
